# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ralph < Formula
  desc "ralph — a CLI for harness engineering with Claude Code"
  homepage "https://github.com/yoshpy-dev/ralph"
  version "3.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yoshpy-dev/ralph/releases/download/v3.5.1/ralph_3.5.1_darwin_amd64.tar.gz"
      sha256 "4b614fcbe48c0ab584841134adf6ba53124af737461b8f1bbd1c6545d856a9f4"

      define_method(:install) do
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yoshpy-dev/ralph/releases/download/v3.5.1/ralph_3.5.1_darwin_arm64.tar.gz"
      sha256 "bba4cd836e0b6d18e3fdce5485e2eb32e21c4486236b1df90d349766d1916a93"

      define_method(:install) do
        bin.install "ralph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoshpy-dev/ralph/releases/download/v3.5.1/ralph_3.5.1_linux_amd64.tar.gz"
      sha256 "4bf4235161a01b9b938eaa19d3e5e36066d00fe827d9e9851432ca902efce508"
      define_method(:install) do
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoshpy-dev/ralph/releases/download/v3.5.1/ralph_3.5.1_linux_arm64.tar.gz"
      sha256 "8fa9c95fc52c83c6b8eebd4d51801b1a4e0fa53bc86c99f8dfd0e33095d4569f"
      define_method(:install) do
        bin.install "ralph"
      end
    end
  end

  test do
    system "#{bin}/ralph", "version"
  end
end
